name: CD-SPA-AS
run-name: Deploy Single Page Web Application to an Azure App Service

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      project_name:
        type: string
        required: true
      app_name:
        type: string
        required: true
      repo_name:
        type: string
        required: true
      build_number:
        type: string
        required: true
      azure_service_principal:
        type: string
        required: true
      environment_name:
        type: string
        required: true
      runner_name:
        type: string
        required: true
      env_filename:
        type: string
        required: true

  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_NAME: ${{ inputs.project_name }}
  APP_NAME: ${{ inputs.app_name }}
  REPO_NAME: ${{ inputs.repo_name }}
  BUILD_NUMBER: ${{ inputs.build_number }}
  SERVICE_PRINCIPAL: ${{secrets[inputs.azure_service_principal]}}
  ENVIRONMENT_NAME: ${{ inputs.environment_name }}
  ENV_FILENAME: ${{ inputs.env_filename }}

# A workflow run is made up of one or more jobs
jobs:
  push-deploy:
    runs-on: ${{ inputs.runner_name }}
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: write
      security-events: read
      statuses: read
    environment: 
      name: ${{ inputs.environment_name }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.REPO_NAME }}-${{ env.BUILD_NUMBER }}

      - name: Expanding Artifact
        run: |
          chmod 777 ${{ env.REPO_NAME }}-$BUILD_NUMBER.tar
          mkdir -p ${{ env.REPO_NAME }}
          chmod 777 ${{ env.REPO_NAME }}
          tar -xvf ${{ env.REPO_NAME }}-$BUILD_NUMBER.tar -C ${{ env.REPO_NAME }}

      - name: Replace placeholder
        run: |
          cd ${{ github.workspace }}/${{ env.REPO_NAME }}/build
          .\replaceplaceholder.ps1 -placeholderprefix UIPLACEHOLDER_ -valuesenvfile ${{ env.ENV_FILENAME }} -targetfile .\static\js\main.*.js
        shell: pwsh

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ env.SERVICE_PRINCIPAL }}
          package: './${{ env.REPO_NAME }}/build'

      - name: Update the confluence
        uses: revenue-solutions-inc/confluence-rsi@v1
        with:
          service: ${{ env.PROJECT_NAME }}
          env: ${{ env.ENVIRONMENT_NAME }}
          version: ${{ env.BUILD_NUMBER }}
          token: ${{ secrets.CONFLUENCE_TOKEN }}
          connectionstring: ${{ secrets.COSMOS_CONNECTION_STRING }}
