name: IAC-FA
run-name: Infrastructure As Code for Function App

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      runner_name:
        type: string
        required: true
      azure_credentials:
        type: string
        required: true
      subscription:
        type: string
        required: true
      resource_group:
        type: string
        required: true
      parameters:
        type: string
        required: true

  workflow_dispatch:

  # Environment variables available to all jobs and steps in this workflow
env:
  AZURE_CREDENTIALS: ${{secrets[inputs.azure_credentials]}}
  AZURE_SUBSCRIPTION: ${{ inputs.subscription }}
  AZURE_RG: ${{ inputs.resource_group }}
  PARAMETERS: ${{ inputs.parameters }}

# A workflow run is made up of one or more jobs
jobs:
  arm-deploy:
    runs-on: ${{ inputs.runner_name }}
    environment: ${{ inputs.environment_name }}
    steps:
        # Checkout Bicep Templates
      - uses: actions/checkout@v2
        with:
          ref: function-app
          repository: revenue-solutions-inc/bicep-templates
          token: ${{ secrets.PAT }}
          path: bicep-templates

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

        # Deploy Bicep file
      - name: deploy function app
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RG }}
          template: ./bicep-templates/Modules/FunctionApp.bicep
          parameters: ${{ env.PARAMETERS }}
          failOnStdErr: false

      