name: CI-CD-FA-PY
run-name: Deploy Any Python Function app

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      runner_name:
        type: string
        required: true
      azure_publish_profile:
        type: string
        required: true
      function_name:
        type: string
        required: true
      function_package_path:
        type: string
        required: true
      tag_version:
        type: string
        required: true
      repository_name:
        type: string
        required: true

  workflow_dispatch:

  # Environment variables available to all jobs and steps in this workflow
env:
  AZURE_FUNCTIONAPP_NAME: ${{ inputs.function_name }}   # set this to your function app name on Azure
  PUBLISH_PROFILE: ${{secrets[inputs.azure_publish_profile]}}
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ${{ inputs.function_package_path }}       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.11'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')
  SERVICE_VERSION: ${{ inputs.tag_version }}
  REPOSITORY_NAME: ${{ inputs.repository_name }}

# A workflow run is made up of one or more jobs
jobs:
  build-push-deploy:
    runs-on: ${{ inputs.runner_name }}
    environment: ${{ inputs.environment_name }}
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SERVICE_VERSION }}
          repository: revenue-solutions-inc/${{ env.REPOSITORY_NAME }}
          token: ${{ secrets.PAT }}


      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ env.PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
